--TEST--
Bug #73254 (Incorrect indentation generated by json_encode() with JSON_PRETTY_PRINT)
--SKIPIF--
<?php
if (!extension_loaded('jsond')) die('skip');
?>
--FILE--
<?php
require_once "bootstrap.inc";

echo $jsond_encode([$jsond_encode([1], jsond_constant('PRETTY_PRINT'))]), "\n";

$fp = fopen('php://temp', 'r');
$data = ['a' => $fp];
echo $jsond_encode($data), "\n";
echo $jsond_encode([$jsond_encode([1], jsond_constant('PRETTY_PRINT'))]), "\n";

?>
--EXPECT--
["[\n    1\n]"]

["[\n    1\n]"]
