--TEST--
Bug #73254 (Incorrect indentation generated by jsond_encode() with JSON_PRETTY_PRINT)
--EXTENSIONS--
jsond
--FILE--
<?php
require_once "bootstrap.inc";

echo jsond_encode([jsond_encode([1], JSOND_PRETTY_PRINT)]), "\n";

$fp = fopen('php://temp', 'r');
$data = ['a' => $fp];
echo jsond_encode($data), "\n";
echo jsond_encode([jsond_encode([1], JSOND_PRETTY_PRINT)]), "\n";

?>
--EXPECT--
["[\n    1\n]"]

["[\n    1\n]"]
