/* Generated by re2c 4.0.2 on Sat Apr  26 13:18:41 2025 */
/*
 * Copyright (c) 2012-2023 Jakub Zelenka. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>

#include "jso_scanner.h"
#include "jso_parser.h"
#include "jso_parser.tab.h"

#include "jso_scanner_defs.h"

#define	YYCTYPE     jso_ctype
#define	YYCURSOR    JSO_IO_CURSOR(s->io)
#define	YYLIMIT     JSO_IO_LIMIT(s->io)
#define	YYMARKER    JSO_IO_MARKER(s->io)
#define	YYCTXMARKER JSO_IO_CTXMARKER(s->io)

#define YYGETCONDITION()        s->state
#define YYSETCONDITION(yystate) s->state = yystate

#define	YYFILL(n)   { JSO_IO_READ(s->io, n); \
	if (JSO_IO_ERROR(s->io)) return JSO_T_ERROR; \
	if (JSO_IO_END(s->io)) return JSO_T_EOI; }

#define JSO_CONDITION_SET(condition) YYSETCONDITION(yyc##condition)
#define JSO_CONDITION_GOTO(condition) goto yyc_##condition

#define JSO_SCANNER_START_GOTO() goto scanner_start

#define JSO_SCANNER_COPY_ESC() jso_scanner_copy_string(s, 0)
#define JSO_SCANNER_COPY_UTF() jso_scanner_copy_string(s, 5)

#define JSO_SCANNER_LOC(location) JSO_SCANNER_LOCATION(*s, location)

#define JSO_SCANNER_ERROR(etype) \
	do { \
		JSO_VALUE_SET_ERROR(s->value, jso_error_new_ex(etype, &s->loc)); \
		return JSO_T_ERROR; \
	} while(0)


static void jso_scanner_copy_string(jso_scanner *s, size_t esc_size)
{
	size_t len = JSO_IO_STR_LENGTH(s->io) - esc_size;
	if (len) {
		memcpy(s->pstr, JSO_IO_STR_GET_START(s->io), len * sizeof(jso_ctype));
		s->pstr += len;
	}
}

static int jso_hex_to_int(jso_ctype c)
{
	if (c >= '0' && c <= '9') {
		return c - '0';
	} else if (c >= 'A' && c <= 'F') {
		return c - ('A' - 10);
	} else if (c >= 'a' && c <= 'f') {
		return c - ('a' - 10);
	} else {
		/* this should never happened */
		return -1;
	}
}

static int jso_ucs2_to_int_ex(jso_scanner *s, int size, int start)
{
	int i, code = 0;
	jso_ctype *pc = JSO_IO_CURSOR(s->io) - start;
	for (i = 0; i < size; i++) {
		code |= jso_hex_to_int(*(pc--)) << (i * 4);
	}
	return code;
}

static int jso_ucs2_to_int(jso_scanner *s, int size)
{
	return jso_ucs2_to_int_ex(s, size, 1);
}

void jso_scanner_init(jso_scanner *s, jso_io *io)
{
	memset(s, 0, sizeof (jso_scanner));
	s->io = io;
	JSO_SCANNER_LOC(last_column) = 1;
	JSO_SCANNER_LOC(last_line) = 1;
	JSO_CONDITION_SET(JS);
}

int jso_scan(jso_scanner *s)
{
	/* init value to null to prevent double freeing when it's not used in parser */
	JSO_VALUE_SET_NULL(s->value);

scanner_start:
	/* init location values */
	JSO_SCANNER_LOC(first_column) = JSO_SCANNER_LOC(last_column);
	JSO_SCANNER_LOC(first_line) = JSO_SCANNER_LOC(last_line);

	/* set token postion to the cursor position */
	JSO_IO_RESET_TOKEN(s->io);


	{
		YYCTYPE yych;
		unsigned int yyaccept = 0;
		static const unsigned char yybm_JS[256] = {
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,  64,   0,   0,   0,  64,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			 64,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			128, 128, 128, 128, 128, 128, 128, 128,
			128, 128,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0,
			  0,   0,   0,   0,   0,   0,   0,   0
		};
		if (YYGETCONDITION() < 1) {
			goto yyc_JS;
		} else {
			if (YYGETCONDITION() < 2) goto yyc_STR_P1;
			else goto yyc_STR_P2;
		}
/* *********************************** */
yyc_JS:
		yych = *YYCURSOR;
		if (yybm_JS[0+yych] & 128) goto yy11;
		if (yych <= ':') {
			if (yych <= 0x1F) {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy1;
					if (yych <= 0x08) goto yy2;
					goto yy4;
				} else {
					if (yych <= '\n') goto yy6;
					if (yych == '\r') goto yy7;
					goto yy2;
				}
			} else {
				if (yych <= '+') {
					if (yych <= ' ') goto yy4;
					if (yych == '"') goto yy8;
					goto yy2;
				} else {
					if (yych <= ',') goto yy9;
					if (yych <= '-') goto yy10;
					if (yych <= '/') goto yy2;
					goto yy13;
				}
			}
		} else {
			if (yych <= 'm') {
				if (yych <= '\\') {
					if (yych == '[') goto yy14;
					goto yy2;
				} else {
					if (yych <= ']') goto yy15;
					if (yych == 'f') goto yy16;
					goto yy2;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= 'n') goto yy17;
					if (yych == 't') goto yy18;
					goto yy2;
				} else {
					if (yych <= '{') goto yy19;
					if (yych == '}') goto yy20;
					goto yy2;
				}
			}
		}
yy1:
		++YYCURSOR;
		{
		if (JSO_IO_END(s->io)) {
			return JSO_T_EOI;
		} else {
			JSO_SCANNER_ERROR(JSO_ERROR_TOKEN);
		}
	}
yy2:
		++YYCURSOR;
yy3:
		{
		JSO_SCANNER_ERROR(JSO_ERROR_TOKEN);
	}
yy4:
		yych = *++YYCURSOR;
yy5:
		if (yybm_JS[0+yych] & 64) goto yy4;
		{
		JSO_SCANNER_LOC(last_column) += JSO_IO_TOKEN_LENGTH(s->io);
		JSO_SCANNER_START_GOTO();
	}
yy6:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_line)++;
		JSO_SCANNER_LOC(last_column) = 1;
		JSO_SCANNER_START_GOTO();
	}
yy7:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy6;
		goto yy5;
yy8:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		JSO_IO_STR_SET_START(s->io);
		JSO_IO_STR_CLEAR_ESC(s->io);
		JSO_CONDITION_SET(STR_P1);
		JSO_CONDITION_GOTO(STR_P1);
	}
yy9:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		return ',';
	}
yy10:
		yych = *++YYCURSOR;
		if (yybm_JS[0+yych] & 128) goto yy11;
		goto yy3;
yy11:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm_JS[0+yych] & 128) goto yy11;
		if (yych <= 'D') {
			if (yych == '.') goto yy21;
		} else {
			if (yych <= 'E') goto yy23;
			if (yych == 'e') goto yy23;
		}
yy12:
		{
		jso_bool bigint = 0, negative = JSO_IO_TOKEN(s->io)[0] == '-';
		size_t digits = JSO_IO_TOKEN_LENGTH(s->io);
		JSO_SCANNER_LOC(last_column) += digits;
		digits -= negative;
		if (digits >= JSO_INT_MAX_LENGTH) {
			if (digits == JSO_INT_MAX_LENGTH) {
				int cmp = strncmp((char *) JSO_IO_TOKEN(s->io) + negative, JSO_INT_MAX_DIGITS, JSO_INT_MAX_LENGTH);
				if (!(cmp < 0 || (cmp == 0 && negative))) {
					bigint = 1;
				}
			} else {
				bigint = 1;
			}
		}
		if (bigint) {
			JSO_VALUE_SET_DOUBLE(s->value, strtod((char *) JSO_IO_TOKEN(s->io), NULL));
			return JSO_T_DOUBLE;
		} else {
			JSO_VALUE_SET_INT(s->value, strtol((char *) JSO_IO_TOKEN(s->io), NULL, 10));
			return JSO_T_LONG;
		}
	}
yy13:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		return ':';
	}
yy14:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		return '[';
	}
yy15:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		return ']';
	}
yy16:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'a') goto yy24;
		goto yy3;
yy17:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'u') goto yy25;
		goto yy3;
yy18:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'r') goto yy26;
		goto yy3;
yy19:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		return '{';
	}
yy20:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		return '}';
	}
yy21:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy22;
		if (yych <= '0') goto yy27;
		if (yych <= '9') goto yy29;
yy22:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept == 0) goto yy12;
			else goto yy3;
		} else {
			goto yy28;
		}
yy23:
		yych = *++YYCURSOR;
		if (yych <= ',') {
			if (yych == '+') goto yy30;
			goto yy22;
		} else {
			if (yych <= '-') goto yy30;
			if (yych <= '/') goto yy22;
			if (yych <= '9') goto yy31;
			goto yy22;
		}
yy24:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy32;
		goto yy22;
yy25:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy33;
		goto yy22;
yy26:
		yych = *++YYCURSOR;
		if (yych == 'u') goto yy34;
		goto yy22;
yy27:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'E') goto yy23;
		if (yych == 'e') goto yy23;
yy28:
		{
		JSO_SCANNER_LOC(last_column) += JSO_IO_TOKEN_LENGTH(s->io);
		JSO_VALUE_SET_DOUBLE(s->value, strtod((char *) JSO_IO_TOKEN(s->io), NULL));
		return JSO_T_DOUBLE;
	}
yy29:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'D') {
			if (yych <= '/') goto yy28;
			if (yych <= '9') goto yy29;
			goto yy28;
		} else {
			if (yych <= 'E') goto yy23;
			if (yych == 'e') goto yy23;
			goto yy28;
		}
yy30:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy22;
		if (yych >= ':') goto yy22;
yy31:
		yych = *++YYCURSOR;
		if (yych <= '/') goto yy28;
		if (yych <= '9') goto yy31;
		goto yy28;
yy32:
		yych = *++YYCURSOR;
		if (yych == 's') goto yy35;
		goto yy22;
yy33:
		yych = *++YYCURSOR;
		if (yych == 'l') goto yy36;
		goto yy22;
yy34:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy37;
		goto yy22;
yy35:
		yych = *++YYCURSOR;
		if (yych == 'e') goto yy38;
		goto yy22;
yy36:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 4;
		JSO_VALUE_SET_NULL(s->value);
		return JSO_T_NUL;
	}
yy37:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 4;
		JSO_VALUE_SET_BOOL(s->value, JSO_TRUE);
		return JSO_T_TRUE;
	}
yy38:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 5;
		JSO_VALUE_SET_BOOL(s->value, JSO_FALSE);
		return JSO_T_FALSE;
	}
/* *********************************** */
yyc_STR_P1:
		yych = *YYCURSOR;
		if (yych <= 0xC1) {
			if (yych <= '!') {
				if (yych == '\r') goto yy41;
				if (yych >= ' ') goto yy42;
			} else {
				if (yych <= '[') {
					if (yych <= '"') goto yy43;
					goto yy42;
				} else {
					if (yych <= '\\') goto yy44;
					if (yych <= 0x7F) goto yy42;
					goto yy46;
				}
			}
		} else {
			if (yych <= 0xED) {
				if (yych <= 0xDF) goto yy48;
				if (yych <= 0xE0) goto yy49;
				if (yych <= 0xEC) goto yy50;
				goto yy51;
			} else {
				if (yych <= 0xF0) {
					if (yych <= 0xEF) goto yy50;
					goto yy52;
				} else {
					if (yych <= 0xF3) goto yy53;
					if (yych <= 0xF4) goto yy54;
					goto yy46;
				}
			}
		}
		++YYCURSOR;
yy40:
		{
		JSO_SCANNER_ERROR(JSO_ERROR_CTRL_CHAR);
	}
yy41:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy55;
		goto yy40;
yy42:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		JSO_CONDITION_GOTO(STR_P1);
	}
yy43:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column)++;
		size_t len = JSO_IO_STR_LENGTH(s->io) - JSO_IO_STR_GET_ESC(s->io);
		jso_string *str = jso_string_alloc(len);
		if (str == NULL) {
			return JSO_T_ENOMEM;
		}
		JSO_VALUE_SET_STRING(s->value, str);
		if (len == 0) {
			JSO_CONDITION_SET(JS);
			return JSO_T_ESTRING;
		}
		JSO_STRING_LEN(str) = len;
		if (JSO_IO_STR_GET_ESC(s->io)) {
			s->pstr = JSO_SVAL(s->value);
			JSO_IO_CURSOR(s->io) = JSO_IO_STR_GET_START(s->io);
			JSO_CONDITION_SET(STR_P2);
			JSO_CONDITION_GOTO(STR_P2);
		} else {
			memcpy(JSO_SVAL(s->value), JSO_IO_STR_GET_START(s->io), len * sizeof(jso_ctype));
			JSO_CONDITION_SET(JS);
			return JSO_T_STRING;
		}
	}
yy44:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'e') {
			if (yych <= '/') {
				if (yych == '"') goto yy56;
				if (yych >= '/') goto yy56;
			} else {
				if (yych <= '\\') {
					if (yych >= '\\') goto yy56;
				} else {
					if (yych == 'b') goto yy56;
				}
			}
		} else {
			if (yych <= 'q') {
				if (yych <= 'f') goto yy56;
				if (yych == 'n') goto yy56;
			} else {
				if (yych <= 's') {
					if (yych <= 'r') goto yy56;
				} else {
					if (yych <= 't') goto yy56;
					if (yych <= 'u') goto yy57;
				}
			}
		}
yy45:
		{
		JSO_SCANNER_ERROR(JSO_ERROR_ESCAPE);
	}
yy46:
		++YYCURSOR;
yy47:
		{
		JSO_SCANNER_ERROR(JSO_ERROR_UTF8);
	}
yy48:
		yych = *++YYCURSOR;
		if (yych <= 0x7F) goto yy47;
		if (yych <= 0xBF) goto yy59;
		goto yy47;
yy49:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 0x9F) goto yy47;
		if (yych <= 0xBF) goto yy60;
		goto yy47;
yy50:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 0x7F) goto yy47;
		if (yych <= 0xBF) goto yy60;
		goto yy47;
yy51:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 0x7F) goto yy47;
		if (yych <= 0x9F) goto yy60;
		goto yy47;
yy52:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 0x8F) goto yy47;
		if (yych <= 0xBF) goto yy61;
		goto yy47;
yy53:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 0x7F) goto yy47;
		if (yych <= 0xBF) goto yy61;
		goto yy47;
yy54:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 0x7F) goto yy47;
		if (yych <= 0x8F) goto yy61;
		goto yy47;
yy55:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_line)++;
		JSO_SCANNER_LOC(last_column) = 1;
		JSO_CONDITION_GOTO(STR_P1);
	}
yy56:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 2;
		JSO_IO_STR_ADD_ESC(s->io, 1);
		JSO_CONDITION_GOTO(STR_P1);
	}
yy57:
		yych = *++YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '9') {
				if (yych <= '/') goto yy58;
				if (yych <= '0') goto yy62;
				goto yy63;
			} else {
				if (yych <= '@') goto yy58;
				if (yych <= 'C') goto yy63;
				goto yy64;
			}
		} else {
			if (yych <= 'c') {
				if (yych <= 'F') goto yy63;
				if (yych >= 'a') goto yy63;
			} else {
				if (yych <= 'd') goto yy64;
				if (yych <= 'f') goto yy63;
			}
		}
yy58:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept == 0) goto yy45;
			else goto yy47;
		} else {
			goto yy82;
		}
yy59:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 2;
		JSO_CONDITION_GOTO(STR_P1);
	}
yy60:
		yych = *++YYCURSOR;
		if (yych <= 0x7F) goto yy58;
		if (yych <= 0xBF) goto yy65;
		goto yy58;
yy61:
		yych = *++YYCURSOR;
		if (yych <= 0x7F) goto yy58;
		if (yych <= 0xBF) goto yy66;
		goto yy58;
yy62:
		yych = *++YYCURSOR;
		if (yych <= '9') {
			if (yych <= '/') goto yy58;
			if (yych <= '0') goto yy67;
			if (yych <= '7') goto yy68;
			goto yy69;
		} else {
			if (yych <= 'F') {
				if (yych <= '@') goto yy58;
				goto yy69;
			} else {
				if (yych <= '`') goto yy58;
				if (yych <= 'f') goto yy69;
				goto yy58;
			}
		}
yy63:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy69;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy69;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy69;
			goto yy58;
		}
yy64:
		yych = *++YYCURSOR;
		if (yych <= 'B') {
			if (yych <= '7') {
				if (yych <= '/') goto yy58;
				goto yy69;
			} else {
				if (yych <= '9') goto yy70;
				if (yych <= '@') goto yy58;
				goto yy70;
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'F') goto yy71;
				goto yy58;
			} else {
				if (yych <= 'b') goto yy70;
				if (yych <= 'f') goto yy71;
				goto yy58;
			}
		}
yy65:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 3;
		JSO_CONDITION_GOTO(STR_P1);
	}
yy66:
		yych = *++YYCURSOR;
		if (yych <= 0x7F) goto yy58;
		if (yych <= 0xBF) goto yy72;
		goto yy58;
yy67:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '7') goto yy73;
			if (yych <= '9') goto yy74;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy74;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy74;
			goto yy58;
		}
yy68:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy74;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy74;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy74;
			goto yy58;
		}
yy69:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy75;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy75;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy75;
			goto yy58;
		}
yy70:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy76;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy76;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy76;
			goto yy58;
		}
yy71:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy77;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy77;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy77;
			goto yy58;
		}
yy72:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 4;
		JSO_CONDITION_GOTO(STR_P1);
	}
yy73:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy78;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy78;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy78;
			goto yy58;
		}
yy74:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy79;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy79;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy79;
			goto yy58;
		}
yy75:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy80;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy80;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy80;
			goto yy58;
		}
yy76:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy81;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy81;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy81;
			goto yy58;
		}
yy77:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych <= '9') goto yy83;
			goto yy58;
		} else {
			if (yych <= 'F') goto yy83;
			if (yych <= '`') goto yy58;
			if (yych <= 'f') goto yy83;
			goto yy58;
		}
yy78:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 6;
		JSO_IO_STR_ADD_ESC(s->io, 5);
		JSO_CONDITION_GOTO(STR_P1);
	}
yy79:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 6;
		JSO_IO_STR_ADD_ESC(s->io, 4);
		JSO_CONDITION_GOTO(STR_P1);
	}
yy80:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 6;
		JSO_IO_STR_ADD_ESC(s->io, 3);
		JSO_CONDITION_GOTO(STR_P1);
	}
yy81:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == '\\') goto yy84;
yy82:
		{
		JSO_SCANNER_ERROR(JSO_ERROR_UTF16);
	}
yy83:
		++YYCURSOR;
		goto yy82;
yy84:
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy58;
		yych = *++YYCURSOR;
		if (yych == 'D') goto yy85;
		if (yych != 'd') goto yy58;
yy85:
		yych = *++YYCURSOR;
		if (yych <= 'B') goto yy58;
		if (yych <= 'F') goto yy86;
		if (yych <= 'b') goto yy58;
		if (yych >= 'g') goto yy58;
yy86:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych >= ':') goto yy58;
		} else {
			if (yych <= 'F') goto yy87;
			if (yych <= '`') goto yy58;
			if (yych >= 'g') goto yy58;
		}
yy87:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy58;
			if (yych >= ':') goto yy58;
		} else {
			if (yych <= 'F') goto yy88;
			if (yych <= '`') goto yy58;
			if (yych >= 'g') goto yy58;
		}
yy88:
		++YYCURSOR;
		{
		JSO_SCANNER_LOC(last_column) += 12;
		JSO_IO_STR_ADD_ESC(s->io, 8);
		JSO_CONDITION_GOTO(STR_P1);
	}
/* *********************************** */
yyc_STR_P2:
		yych = *YYCURSOR;
		if (yych == '"') goto yy90;
		if (yych == '\\') goto yy91;
		++YYCURSOR;
		{ JSO_CONDITION_GOTO(STR_P2); }
yy90:
		++YYCURSOR;
		YYSETCONDITION(yycJS);
		{
		JSO_SCANNER_COPY_ESC();
		return JSO_T_STRING;
	}
yy91:
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'u') goto yy93;
yy92:
		{
		char esc;
		JSO_SCANNER_COPY_ESC();
		switch (*JSO_IO_CURSOR(s->io)) {
			case 'b':
				esc = '\b';
				break;
			case 'f':
				esc = '\f';
				break;
			case 'n':
				esc = '\n';
				break;
			case 'r':
				esc = '\r';
				break;
			case 't':
				esc = '\t';
				break;
			case '\\':
			case '/':
			case '"':
				esc = *JSO_IO_CURSOR(s->io);
				break;
			default:
				JSO_SCANNER_ERROR(JSO_ERROR_ESCAPE);
		}
		*(s->pstr++) = esc;
		++YYCURSOR;
		JSO_IO_STR_SET_START(s->io);
		JSO_CONDITION_GOTO(STR_P2);
	}
yy93:
		yych = *++YYCURSOR;
		if (yych <= 'D') {
			if (yych <= '9') {
				if (yych <= '/') goto yy94;
				if (yych <= '0') goto yy95;
				goto yy96;
			} else {
				if (yych <= '@') goto yy94;
				if (yych <= 'C') goto yy96;
				goto yy97;
			}
		} else {
			if (yych <= 'c') {
				if (yych <= 'F') goto yy96;
				if (yych >= 'a') goto yy96;
			} else {
				if (yych <= 'd') goto yy97;
				if (yych <= 'f') goto yy96;
			}
		}
yy94:
		YYCURSOR = YYMARKER;
		goto yy92;
yy95:
		yych = *++YYCURSOR;
		if (yych <= '9') {
			if (yych <= '/') goto yy94;
			if (yych <= '0') goto yy98;
			if (yych <= '7') goto yy99;
			goto yy100;
		} else {
			if (yych <= 'F') {
				if (yych <= '@') goto yy94;
				goto yy100;
			} else {
				if (yych <= '`') goto yy94;
				if (yych <= 'f') goto yy100;
				goto yy94;
			}
		}
yy96:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy100;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy100;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy100;
			goto yy94;
		}
yy97:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '7') goto yy100;
			if (yych <= '9') goto yy101;
			goto yy94;
		} else {
			if (yych <= 'B') goto yy101;
			if (yych <= '`') goto yy94;
			if (yych <= 'b') goto yy101;
			goto yy94;
		}
yy98:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '7') goto yy102;
			if (yych <= '9') goto yy103;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy103;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy103;
			goto yy94;
		}
yy99:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy103;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy103;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy103;
			goto yy94;
		}
yy100:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy104;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy104;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy104;
			goto yy94;
		}
yy101:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy105;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy105;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy105;
			goto yy94;
		}
yy102:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy106;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy106;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy106;
			goto yy94;
		}
yy103:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy107;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy107;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy107;
			goto yy94;
		}
yy104:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy108;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy108;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy108;
			goto yy94;
		}
yy105:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych <= '9') goto yy109;
			goto yy94;
		} else {
			if (yych <= 'F') goto yy109;
			if (yych <= '`') goto yy94;
			if (yych <= 'f') goto yy109;
			goto yy94;
		}
yy106:
		++YYCURSOR;
		{
		int utf16 = jso_ucs2_to_int(s, 2);
		JSO_SCANNER_COPY_UTF();
		*(s->pstr++) = (jso_ctype) utf16;
		JSO_IO_STR_SET_START(s->io);
		JSO_CONDITION_GOTO(STR_P2);
	}
yy107:
		++YYCURSOR;
		{
		int utf16 = jso_ucs2_to_int(s, 3);
		JSO_SCANNER_COPY_UTF();
		*(s->pstr++) = (jso_ctype) (0xc0 | (utf16 >> 6));
		*(s->pstr++) = (jso_ctype) (0x80 | (utf16 & 0x3f));
		JSO_IO_STR_SET_START(s->io);
		JSO_CONDITION_GOTO(STR_P2);
	}
yy108:
		++YYCURSOR;
		{
		int utf16 = jso_ucs2_to_int(s, 4);
		JSO_SCANNER_COPY_UTF();
		*(s->pstr++) = (jso_ctype) (0xe0 | (utf16 >> 12));
		*(s->pstr++) = (jso_ctype) (0x80 | ((utf16 >> 6) & 0x3f));
		*(s->pstr++) = (jso_ctype) (0x80 | (utf16 & 0x3f));
		JSO_IO_STR_SET_START(s->io);
		JSO_CONDITION_GOTO(STR_P2);
	}
yy109:
		yych = *++YYCURSOR;
		if (yych != '\\') goto yy94;
		yych = *++YYCURSOR;
		if (yych != 'u') goto yy94;
		yych = *++YYCURSOR;
		if (yych == 'D') goto yy110;
		if (yych != 'd') goto yy94;
yy110:
		yych = *++YYCURSOR;
		if (yych <= 'B') goto yy94;
		if (yych <= 'F') goto yy111;
		if (yych <= 'b') goto yy94;
		if (yych >= 'g') goto yy94;
yy111:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych >= ':') goto yy94;
		} else {
			if (yych <= 'F') goto yy112;
			if (yych <= '`') goto yy94;
			if (yych >= 'g') goto yy94;
		}
yy112:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '/') goto yy94;
			if (yych >= ':') goto yy94;
		} else {
			if (yych <= 'F') goto yy113;
			if (yych <= '`') goto yy94;
			if (yych >= 'g') goto yy94;
		}
yy113:
		++YYCURSOR;
		{
		int utf32, utf16_hi, utf16_lo;
		utf16_hi = jso_ucs2_to_int(s, 4);
		utf16_lo = jso_ucs2_to_int_ex(s, 4, 7);
		utf32 = ((utf16_lo & 0x3FF) << 10) + (utf16_hi & 0x3FF) + 0x10000;
		jso_scanner_copy_string(s, 11);
		*(s->pstr++) = (jso_ctype) (0xf0 | (utf32 >> 18));
		*(s->pstr++) = (jso_ctype) (0x80 | ((utf32 >> 12) & 0x3f));
		*(s->pstr++) = (jso_ctype) (0x80 | ((utf32 >> 6) & 0x3f));
		*(s->pstr++) = (jso_ctype) (0x80 | (utf32 & 0x3f));
		JSO_IO_STR_SET_START(s->io);
		JSO_CONDITION_GOTO(STR_P2);
	}
	}


}

